project:
  type: website
  output-dir: docs

website:
  title: "Ejemplos variados en R"
  navbar:
    left:
      - index.qmd
      - href: https://github.com/thonyguev/Ejemplos-variados-en-R
        icon: github
        text: repositorio

format:
  html:
    theme: 
      light: litera
      dark: superhero
    css: styles.css
    toc: true

editor: visual

