project:
  type: website
  output-dir: docs

website:
  title: "Ejemplos variados en R"
  navbar:
    right: 
      - index.qmd
      - icon: github
        href: https://github.com/thonyguev/Ejemplos-variados-en-R

format:
  html:
    theme: cosmo
    css: styles.css

editor: source

