---
title: "Asignacion # 2 - Agosto: Manipulación de Datadaframes y cálculos"
date: "2023-08-11"
---

```{r, message=FALSE}
library(readxl)
library(DT)
library(tibble)
library(purrr)
```

```{r}
file <- read_xlsx(path = "./data1.xlsx")
file.values <- read_xlsx(path = "./data2.xlsx")
```

```{r}
file %>% datatable()
```

```{r}
file.values %>% datatable()
```

```{r}
`Columna A, Fila 1` <- rep(file.values[1,2] %>% as.numeric ,nrow(file))
`Columna A, Fila 2` <- rep(file.values[2,2] %>% as.numeric ,nrow(file))
`Columna A, Fila 3` <- rep(file.values[3,2] %>% as.numeric ,nrow(file))
```

```{r}
df <- file %>% 
  add_column(., `Columna A, Fila 1`,.after = "instalada") %>%
  add_column(., `Columna A, Fila 2`,.after = "generacion") %>%
  add_column(., `Columna A, Fila 3`,.after = "firme")
```

```{r}
df %>% datatable
```

```{r}
`result preview` <- (df[1,2] * df[1,3]) + (df[1,4] * df[1,5]) + (df[1,6] * df[1,7])
```

```{r}
`result preview`
```

```{r}
operation <- map(1:nrow(df), function(x){
  math.operation <- (df[x,2] * df[x,3]) + (df[x,4] * df[x,5]) + (df[x,6] * df[x,7])
  math.round <- round(math.operation,2)
  return(math.round)
})
```

```{r}
result <- operation %>% do.call(rbind,.) %>% data.frame()
colnames(result) <- "Resultado"
```

```{r}
result %>% datatable()
```

```{r}
df.result <- df %>% 
  add_column(., result,.after = "planta")
```

## Resultado Final #1
```{r}
df.result %>% datatable()
```

